title: Chris Buckley
description: Copy commonly used Unicode characters using a mobile device.

url: https://cmbuckley.co.uk
baseurl: /charcopy

repository: cmbuckley/charcopy
remote_theme: "cmbuckley/cmbuckley.github.io"

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
